### ISSUE TITLE
Dollar sign ($) loses scanability without line all the way through

### ISSUE THREAD

**Issue by ruffin--** [JetBrains/JetBrainsMono#110]
It's difficult to eyeball a `$` in code when scanning. Looks too much like an `S`. Could be easily remedied by putting the line all the way through the `S` section of the `$`.

Example of two `$`s (with JSLint warning under each, not that that matters) in some code.

![dollarSign](https://user-images.githubusercontent.com/5659878/73399847-f713b880-42b5-11ea-9a47-8cda19457e18.png)

`scope.$on` in particular looks a lot like `scope.Son` on a scan. Whether one agrees there or not, I think we could all agree that keeping the line would make that `$` much more obvious.

**Comment by qgates** [comment]
The current style of `$` is pleasing on the eye, but is easy to mis-scan in certain domains. I agree that a more traditional `$` would be easier to scan, so long as the aesthetic isn't compromised. Perhaps another stylistic set could be an option here?

**Comment by philippnurullin** [comment]
I just realised that i didn't ask, is the new construction works better? The main point of the old one, was to remove the vertical line, so it will render better in small sizes & had a more pronounced form.

**Comment by qgates** [comment]
@philippnurullin Yes, that's kind of what I was getting at above. For coding, in the example given by the OP, the new `$` works better, but for terminal/console use I prefer the old one. That's personal preference though. Given that stylistic sets can be used to vary specific character styles, I thought that option would be best, but the new `$` works for me as a default.

If there is any desire to reintroduce the old symbol, since descenders have now grown a little on d p etc., perhaps there's room to extend the top and bottom of the vertical line a touch to make it a little clearer?

**Comment by philippnurullin** [comment]
@qgates As you suggesting it can only be in `sset` feature. And we have a lot to do, before adding the alternates. So, it may return, but not soon, on the other hand, we have all the glyphs made, so its only "scripting" magic. We'll see. Not in v1.0.4 for sure.
