### ISSUE TITLE
Fish operator displays as greater than or equal followed by greater than

### ISSUE THREAD

**Issue by dam5s** [JetBrains/JetBrainsMono#134]
The fish operator `>=>` displays as `≥>`
Disabling the ligature in that case would be a good first solution.

Thanks.

**Comment by philippnurullin** [comment]
@dam5s Hi, what IDE & version of JetBrains Mono you using?

**Comment by larjo** [comment]
I have the latest update of Rider 2019.3 and I have also downloaded and installed JetBrains Mono 1.03 (all variants).

In vscode the fish operator works if I choose "JetBrains Mono".

In Rider the fish operator is broken when I choose "JetBrains Mono" but it works however if I choose "JetBrains Mono Medium" or "JetBrains Mono ExtraBold".

**Comment by philippnurullin** [comment]
@larjo Thats because in Rider there is an old version of JetBrains Mono is bundled. You need to remove it manually. 

1. `IDEA\jbr\lib\fonts`
2. If you using Toolbox `C:\Users\ username\AppData\Local\JetBrains\Toolbox\apps\CLion\ch-0\193.6015.37\jbr\lib\fonts\`
_The exact paths will be different in your case. Let me know if you have difficulties with it._

And it's important to restart.

After that the Rider will use the font installed in your OS.

https://github.com/JetBrains/JetBrainsMono/issues/49
https://github.com/JetBrains/JetBrainsMono/issues/21

**Comment by larjo** [comment]
Thanks!
I removed C:\Program Files\JetBrains\JetBrains Rider 2019.1.1\jbr\lib\fonts\JetBrainsMono*
And now the fish-ligature works fine!

**Comment by philippnurullin** [comment]
@dam5s Closing it because the solution is working. Feel free to reopen, if not in your case.
