### ISSUE TITLE
Ligatures for `www` and ligature for hex (`0x111111`)

### ISSUE THREAD

**Issue by gsbhasin123** [JetBrains/JetBrainsMono#179]
You can see www here:
![image](https://user-images.githubusercontent.com/48339289/76910341-03a29f00-686b-11ea-9577-063dab69e540.png)
Hex here:
![image](https://user-images.githubusercontent.com/48339289/76910380-12895180-686b-11ea-9c4c-d7f50a852604.png)
Pls add asap, this is kinda annoying as i love those ligatures

**Comment by philippnurullin** [comment]
@gsbhasin123 Hi, the `www` ligature looks quite unreadable to me. I'm not sure that we will add it at all. It looks not necessary & more of a subjective thing to like & dislike. I fear that for some people it will be really distracting. The other feature is already requested in here https://github.com/JetBrains/JetBrainsMono/issues/98 Can't say the exact date of its release.

**Comment by gsbhasin123** [comment]
Really? Oh well, it looks quite readable to me, more readable in fact, but ok

**Comment by poyribn** [comment]
My personal Preference for ``www`` Ligatures is to use them as a Cheat to make the Text look just a bit less dense:
Magically combine the 6 ``v`` Shapes of ``www`` into just 5 ``v`` Shapes, as in ``wvw``.
Because that looks very similar and doesn’t interfere with any other Meaning in real Languages (including Scripting and Programming Languages),
it’s recognizable as ``www`` all the same.
