### ISSUE TITLE
Please update your fonts in the official website

### ISSUE THREAD

**Issue by BornForFever** [JetBrains/JetBrainsMono#192]
In the [official website](https://jetbrains.com/mono), the version of the fonts is still v1.0.3, which is older than that in github. I hope that the fonts in the official website can keep up to date. Thanks.

**Comment by philippnurullin** [comment]
We currently woking on automating this process. That brings the delay in versions. But soon it will be fixed. Thanks for mentioning this.

**Comment by rdhar** [comment]
Love the font (one of the few that fits my tiny laptop screen and features ligatures to boot!) and really appreciate your work and support on it :)

Nowadays, stuff like [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) and [GitHub API](https://developer.github.com/v3/repos/releases/#get-the-latest-release) make it too easy to worry about manually updating links like these. Here's a working snippet to extract the download URL of the most recent (non-prerelease, non-draft) release and add it as a link attribute to a `#download-button` with a simple `Promise`:

```js
fetch("https://api.github.com/repos/JetBrains/JetBrainsMono/releases/latest")
  .then((response) => {
    return response.json();
  })
  .then((data) => {
    return document
      .getElementById("download-button")
      .setAttribute("href", data.assets[0].browser_download_url);
  });
```


<details><summary>…</summary>

And here's a screenshot of the above snippet using JetBrains Mono because it's too pretty to _not_ share!

![code_snippet](https://user-images.githubusercontent.com/19497993/78944415-c1f5c480-7ab5-11ea-8631-aacdf86c27d0.png)
</details>

**Comment by philippnurullin** [comment]
@rdhar Wow, thanks. I will send it to the guys.

**Comment by philippnurullin** [comment]
@rdhar  The automation team sends you big thanks! Have a nice day.

**Comment by rdhar** [comment]
@philippnurullin No worries at all, glad to have given something back to a wonderful project! 👍

**Comment by philippnurullin** [comment]
Updated the archive to the latest version.
