### ISSUE TITLE
Missing ligatures for '>->', '<===', '===>',  '[->', '=||', '=|' and '-||'

### ISSUE THREAD

**Issue by ImperadorSid** [JetBrains/JetBrainsMono#194]
I am using VS Code 1.43.2 and JetBrains Mono 1.0.5.

I realized that these symbols are either missing or not being rendered correctly.

**Comment by philippnurullin** [comment]
@ImperadorSid Hi, can you attach the screenshots with the symbols.

**Comment by philippnurullin** [comment]
`=||` `=|` `-||` Thees are non existent in the first place because they are not an operator. Do you know where they used as a logical bit?

`<===` `===>` `[->` sequences excluded because of this problem https://github.com/JetBrains/JetBrainsMono/issues/151

`>->` not working is a simple bug. Will fix it asap.

**Comment by ImperadorSid** [comment]
> @ImperadorSid Hi, can you attach the screenshots with the symbols.

![IMG_20200408_103920_345](https://user-images.githubusercontent.com/18284740/78790691-44cb3200-7985-11ea-85ca-6daf67b0419a.jpg)

**Comment by ImperadorSid** [comment]
Reading the issues mentioned, I realized the problem with '===>'.  Therefore, I expect the correction of the '> ->'
