### ISSUE TITLE
Something went wrong on Vietnamese

### ISSUE THREAD

**Issue by dinhquochan** [JetBrains/JetBrainsMono#209]
Dear,

In version 1.0.3, I can use **SF Mono** is a fallback font to display Vietnamese characters. But in version >= 1.0.4, I can not do that anymore.

Version 1.0.3 no fallback font

![image](https://user-images.githubusercontent.com/9979458/79238277-63f02500-7e99-11ea-919e-b80c07773963.png)

Version 1.0.3 with fallback font

![image](https://user-images.githubusercontent.com/9979458/79238334-723e4100-7e99-11ea-834d-0d29772a7603.png)

Version (1.0.4, 1.0.5) no fallback font

![image](https://user-images.githubusercontent.com/9979458/79237791-c4cb2d80-7e98-11ea-8e49-c69de7419412.png)

Version (1.0.4, 1.0.5) with fallback font

![image](https://user-images.githubusercontent.com/9979458/79238625-d06b2400-7e99-11ea-82ca-ac4aa52afb37.png)

Thanks.

**Comment by philippnurullin** [comment]
Yes, this happening because of added Vietnamese diacritics. Sorry, didn't know it will appear this way. 

The workaround is to revert back to 1.0.3 & wait for the next update with support  of Vietnamese language. As you can see it will be delivered soon. Link to the related request https://github.com/JetBrains/JetBrainsMono/issues/14

**Comment by haipham22** [comment]
đã thấy thánh Hân ở đây rồi =)))

**Comment by dinhquochan** [comment]
Thank @philippnurullin 
@haipham22 resolved.

![image](https://user-images.githubusercontent.com/9979458/80687504-9bdfa500-8af4-11ea-8599-53dfca561a36.png)
