### ISSUE TITLE
Readability problem in JetBrainsMono font: shape of lower-case `u` same as upper-case `U`

### ISSUE THREAD

**Issue by mrauhu** [JetBrains/JetBrainsMono#212]
Greetings @philippnurullin 

I've got your new font *JetBrainsMono* as default font for the PHPStorm 2020.1.

Looks good.

Problem is lower-case `u` has same shape as upper-case `U`.

When you have chance please fix it.

Best wishes,
Sergey.

**Comment by kolyshkin** [comment]
I concur, that'd be a nice improvement (or option).

To my mind, lowercase u should look similar to n upside down.

**Comment by philippnurullin** [comment]
Hi @mrauhu Can you include an example where you having difficulties to differentiate thees letters?
The vertical stem in `u` removed to reduce details.

**Comment by mrauhu** [comment]
@philippnurullin thanks for answer.

There is no difficulties to differentiate letters.

Problem is readability.

Also, there is no logic, removing the vertical stem only from `u`, and keep it in the `n` and `m`.

**Comment by kolyshkin** [comment]
> Problem is readability.

To me, readability is an ability to read, and it includes ability to differentiate between glyphs. I can distinguish u from U just fine in this font. So, no readability problem (for me).

The problem (to my mind) is the inconsistency in style between `u` and e.g. `n`. Surely, it might be seen as a feature rather than a bug, and it's a matter of personal taste, and tastes differ, and ultimately it's up to the designer to say the final word in the matter.

This is why I said earlier that it would be nice to have it as an option.

**Comment by philippnurullin** [comment]
There is is logic, But it's different from what you're used to. The `u` now is rhymed with `o`. & consider geometric nature of the font it works. Aesthetically wise, this gives a slight taste of 20th century german grotesk (yes, sadly in the past someone already came up with that idea)). The functional part i already mentioned.

The typeface is a habit. In case on JetBrains Mono we shifting from more traditional letter form because we believe it works better in small sizes & code environment. But it looks like i'm repeating myself.

There is a possibility on alternate stylistic set, but can't be more specific on that. Don't want tot loose the character of the font in chase of appeal to everybody.

**Comment by jozsefk9** [comment]
I like the "u" without vertical stem. I love it. Matter of taste I guess.
