### ISSUE TITLE
Double star operator not displayed properly

### ISSUE THREAD

**Issue by Jonas1312** [JetBrains/JetBrainsMono#247]
The python double star operator (power/unpacking) is not displayed properly:

![Capture](https://user-images.githubusercontent.com/15847892/82733853-293e9f80-9d17-11ea-897d-19582a29cef3.PNG)

Should look like:
```python
print(2**4)
```

Font version: 1.0.6
OS: Windows
Editor: VSCode 1.45.1
Settings:
```json
"editor.fontFamily": "'JetBrains Mono', Consolas, 'Courier New', monospace",
"editor.fontLigatures": false,
```

Any idea? Thanks

**Comment by philippnurullin** [comment]
Hi @Jonas1312 . Sorry i'm not getting what's wrong. You talking about wrong display of `**` but on screenshot they seem alright. 
Please add more context, include screenshots of expected results.

**Comment by Jonas1312** [comment]
Hi,
in my opinion the `**` should be a little bit higher:

jetbrains mono:
![Capture](https://user-images.githubusercontent.com/15847892/82792474-c14f9c80-9e6f-11ea-8793-43e24a7013a0.PNG)

consolas:
![consolas](https://user-images.githubusercontent.com/15847892/82792486-c7457d80-9e6f-11ea-83b9-b51a016ac18c.PNG)

courier new:
![courier new](https://user-images.githubusercontent.com/15847892/82792499-cca2c800-9e6f-11ea-9d01-29e5b8d42921.PNG)

monospace:
![monospace](https://user-images.githubusercontent.com/15847892/82792511-d2001280-9e6f-11ea-8b86-b0f52d7829c6.PNG)

**Comment by philippnurullin** [comment]
Ok, got you. 
Historically asterisk `*` was made for marking the annotations in books. So it's placement tend to make it more recognizable in the line of text.

In JetBrains Mono `*` is treated more like a `+` `=`. Because the use of this symbol is more common in writing code, so instead of annotation mark it becomes more like  a "proper letter". That's why it made significantly bigger and placed like `+` & same symbols.

<img width="490" alt="Screenshot 2020-05-25 at 11 44 59" src="https://user-images.githubusercontent.com/48058957/82796480-493ca300-9e7e-11ea-861d-42dfba76b6e6.png">

Overall i think the asterisk could be lifted a bit higher if it's in context of numbers. This is possible with certain OpenType features. But it will be note introduced soon.

Thanks for the input. I will close this issue because everything woking like intended.

**Comment by Omnieboer** [comment]
I hadn't realised this reasoning behind the '*', but I do love it in use now that I notice it. Just as with ligatures, it takes some getting used to, but it's great once one is used to them.
