### ISSUE TITLE
Nice to have different view for English and Russian "C" symbol

### ISSUE THREAD

**Issue by MaxShoshin** [JetBrains/JetBrainsMono#27]
Bit different view for russian and english view of "c" symbols will be very useful.

**Comment by philippnurullin** [comment]
I see what problem you addressing. ) We will think of a way to implement that. Can't say the date yet.

**Comment by M-r-A** [comment]
Same for "a", "e", "p", etc.

**Comment by philippnurullin** [comment]
Added a Cyrillic `C` `c` debug mode in [2.300](https://github.com/JetBrains/JetBrainsMono/commit/784f65aca6b8c2b5cf4061b45b079f0e3f391248)
Turn On `cv99` to highlight all Cyrillic `C` `c`.

**Comment by M-r-A** [comment]
@philippnurullin Is there a doc on how to "turn on `cv12345`"?

**Comment by alexeyten** [comment]
@M-r-A you could use instructions from here https://github.com/tonsky/FiraCode/wiki/How-to-enable-stylistic-sets

**Comment by philippnurullin** [comment]
@M-r-A There is no guid yet. 
It will be added with the release of 2.300.

**Comment by Firestar-Reimu** [comment]
Will any fonts design different shape for Cc in Latin/Cyrillic? For example, the are no different between A, B, E, H, I, K, M, N, O, P, T, X in capital Latin/Greek letters.

**Comment by alexeyten** [comment]
@Firestar-Reimu

Cyrillic `С` is the most troublesome because default Russian layout has it on the same key as Latin `C` so it's easy to mistype without notice.

![combined English/Russian keyboard](https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/KB_Eng-Rus_QWERTY%28%D0%99%D0%A6%D0%A3%D0%9A%D0%95%D0%9D%29.svg/640px-KB_Eng-Rus_QWERTY%28%D0%99%D0%A6%D0%A3%D0%9A%D0%95%D0%9D%29.svg.png)
