### ISSUE TITLE
lowercase f looks bad in version 2

### ISSUE THREAD

**Issue by shabahengam** [JetBrains/JetBrainsMono#273]
lowercase f looks bad in new version.
version 1.6.size 10.firefox
![v16](https://user-images.githubusercontent.com/53096747/87355059-ef4e8480-c574-11ea-90b7-b9e3b9695d0a.png)

version 2.size 10.firefox
![v20](https://user-images.githubusercontent.com/53096747/87355068-f2497500-c574-11ea-8994-640b96f5405a.png)

Xterm.size 10(ver 1.6 is up, ver 2 is bottom)
![v16vs20](https://user-images.githubusercontent.com/53096747/87355081-f9708300-c574-11ea-96e8-fb2b5f0818a4.png)

Xterm.size 12(ver 1.6 is up, ver 2 is bottom)
![vv16v20](https://user-images.githubusercontent.com/53096747/87356263-07270800-c577-11ea-94f3-b831a45d2546.png)

**Comment by philippnurullin** [comment]
Hi @shabahengam , this is conchesus change. Isolated `f`, like is your example is looking more pronounced, but is its placed between other letters in a word id creates a "wave" in the x-height. This is becoming more visible if it accompanied by letters like `i`, `j`, `t`. 

I will think on how this can be improved, but the consistency of a line is preferred, so default state of `f` will stay that. For example we can use contextual alternate to switch between 2 different variants of `t`. Surrounded by other letters `f` will have current construction but if it's paired with the `space` & don't by `i`, `j`, `t`, it can be the "old" construction. The drawback is that it won't work if you turn off ligatures.

**Comment by shabahengam** [comment]
Oh now I see that.Thanks for explanation.
left v1.6, right v2
![line](https://user-images.githubusercontent.com/53096747/87567543-9cdaa880-c6d9-11ea-847f-e25c18645ab4.png)

**Comment by trygveaa** [comment]
Maybe the top part of the `f`, above the line, can be made higher?

**Comment by philippnurullin** [comment]
Unfortunately we can't move the ascender in `f`higher. That will break the font logic or we will need to make all the ascenders higher & this will increase the line height which is very sensitive matter of you mind the amount of text on screen.

**Comment by trygveaa** [comment]
Hm, seems like the dot in i and j already is a bit higher though?

**Comment by philippnurullin** [comment]
The dot is higher, but it's a part from different system. The dot don't have the same visual weight like the stem.
The top part of `f` is in connection with `h`, `b`, `d`, `k`, `l`. All these letter need to be changed too if we modify the ascender, and after that, we will be needing to tune the diacritics, which will shift up & eliminate the space between the lines so we will start to increase the line height.

**Comment by BornForFever** [comment]
Hmmm... In my opinion, these letters are not high enough, and should be as high as `()`. However, that would be a tiring job -- All the glyphs, including Latin, Cyrillic and Greek, of all the 8 weights should be modified. 😔

**Comment by qgates** [comment]
Yup. I'm not loving the aesthetic of the new `f` either. While it's more correct, it's less readable. If I understand correctly, the ascender can't be raised as it's already the height of uppercase letters, which would require basically stretching the whole typeface vertically. The alternative might be to slightly lower the horizontal stroke line of `j` `i` `t` etc. in order to restore consistency but give a little extra space for the top half of the `f`.

But I'm not sure how this would look aesthetically, ie. whether it would improve or worsen the overall aesthetic of the font (which is rather nice as-is in 1.6). So it would be an experiment.

**Comment by philippnurullin** [comment]
I will rollback to the previous construction in the next release. 
I'll think on smart way to handle this in later releases.

**Comment by BornForFever** [comment]
Maybe increasing the height of some letters by a little will be a good solution.

**Comment by BornForFever** [comment]
Or making it a stylistic alternative will be a good choice.

**Comment by Aloso** [comment]
@philippnurullin When I code, I care about readability, I don't care about aesthetics. I find JetBrains Mono very readable, the lowercase `f` is the only exception. It would be great if JetBrains Mono offered a alternative `f` with a lower horizontal bar that can be enabled if desired.

Note that Fira Code also has a lowercase `f` where the horizontal line is slightly lower:

![fifjft](https://user-images.githubusercontent.com/15658558/96032694-55da8b80-0e5f-11eb-8853-0bed6b528e86.png)

I actually like this "wave" in x-height, it gives the font a nice personality.

**Comment by Aloso** [comment]
@philippnurullin thank you so much for developing this font! The new version is great 👌

**Comment by arzg** [comment]
I guess this might be more appropriate in a different/new issue, but I think Consolas handles this really well. The top line is Consolas, the middle is JetBrains Mono, and the bottom is SF Mono. Consolas really commits to the idea of the `f` being an exception, and moves its crossbar far below the x-height. This harms consistency but benefits readability, with the tradeoff being clear in the design. SF Mono is the same, but opposite – the `f`’s crossbar aligns with that of all the other letters. I think either approach works because it’s clear that one option was chosen over the other – each font ‘owns’ the tradeoff. JetBrains Mono’s ‘halfway’ stance looks strange in my opinion because it looks like it can’t quite decide which way to go. I’d rather it either embrace the inconsistency in the name of readability like Consolas, or go the other way like SF Mono and keep the consistency. That’s just my 2¢ not as a type designer, but as someone who loves typography and typefaces.

<img width="887" alt="Screen Shot 2020-10-26 at 11 42 23 pm" src="https://user-images.githubusercontent.com/31783266/97173577-e6f91d00-17e4-11eb-842b-1d04fbbe398f.png">

**Comment by awhitedev** [comment]
Just wanted to chime in and say that I really like the rollbacked style of lower-case f that we now have in the latest version. 

@philippnurullin Is a possible solution to just leave it as is? Sure it doesn't line up perfectly as in the cases you've outlined above. But it reads perfectly fine in my opinion and isn't that the goal anyways?

On a side note, I'm not sure if this was intentional but the download link available on the JetBrains site is still referencing an older release from September 10th (version 2.001) I had to download the latest release with this rollback from the repo. Not a big deal, just thought you should know.
