### ISSUE TITLE
Mono Medium - Bold and regular weights do not have the same widths.

### ISSUE THREAD

**Issue by dusttland** [JetBrains/JetBrainsMono#282]
Program: Android Studio
Font: Jetbrains Mono Medium 2.001

If you look at the image, you can see that the bold and regular font weights are not lining up on separate lines. This results text jumping back and forward in Android Studio, because it is changing bold and regular weights as you type.

ExtraBold, ExtraLight seem to have the same issue. Only variant, that works properly, to my eyes, seems to be "Jetbrains Mono". 

![image](https://user-images.githubusercontent.com/11049776/89104307-20f29700-d421-11ea-953f-be17ef7473e2.png)

**Comment by philippnurullin** [comment]
Hi @dusttland , please provide the screenshot with the star of the line. This will help to exclude fallback font problems. Also, please add the Android Studio version & your OS. We will try to reproduce the problem.

**Comment by dusttland** [comment]
Sure.

Screenshot:
![image](https://user-images.githubusercontent.com/11049776/89196585-15cf7080-d5b3-11ea-8a06-c0e6ab69ca2a.png)

OS:
Windows 10 Pro, Version 1909, OS Build 18363.959

Android Studio:
Android Studio 4.0, Build #AI-193.6911.18.40.6514223

**Comment by BornForFever** [comment]
Have you installed the bold font? If not, then Android studio will display the "fake bold" characters which may be wider than regular ones.

**Comment by dusttland** [comment]
Yes, I think I have (assuming that if they show up in Windows font settings, they are installed).

Screenshot as well:
![image](https://user-images.githubusercontent.com/11049776/89384538-e893d700-d706-11ea-810a-22de9046b927.png)

And as the image shows, the different weights line up perfectly, so it can't be the font's issue.

I'm sorry for reporting the issue here.

I wonder if there is something that I can do to fix this or is it an issue of the Android Studio...

**Comment by dusttland** [comment]
Though, what I just discovered, is that Android Studio does not show the bold font as an option:
![image](https://user-images.githubusercontent.com/11049776/89386457-c64f8880-d709-11ea-8c2f-b7ffe7bc4f15.png)

**Comment by BornForFever** [comment]
It seems that android studio recognized JBM Medium as another font apart from JBM. Maybe it's android studio's issue.

**Comment by philippnurullin** [comment]
@dusttland There is a font version conflict. Please delete bundled fonts. Here is an issue with directions https://github.com/JetBrains/JetBrainsMono/issues/142

The problem is that the core functionality does not support font weight options. Java legacy sees font from an old perspective. By it's logick in font family there is always 4 fonts maximum: *Regular*, *Bold*, *Italic*, *Bold Italic*. So to Hack this you need to make subfamilies where you link weights manually. But *Bold* can be only linked to *Regular*, so *Medium* have no bolder paring & program decides to auto bold it. 

Goode new is that this problems can be solved when this issue will be closed. https://youtrack.jetbrains.com/issue/IDEA-92825
