### ISSUE TITLE
Variable fonts not usable on Android Studio

### ISSUE THREAD

**Issue by VincentJoshuaET** [JetBrains/JetBrainsMono#284]
![image](https://user-images.githubusercontent.com/19756326/89176245-c5104580-d5bb-11ea-8154-b5af7546a1eb.png)

JetBrains Mono Italic variable fonts are fine.

**Comment by philippnurullin** [comment]
Hi @VincentJoshuaET , you are right. In current versions of IDE based on IDEA platform variable fonts may not work. This is because it isn't officially supported. Partially it's because of this https://youtrack.jetbrains.com/issue/IDEA-92825 issue. So if you want to use JetBrains Mono i recommend installing non variable version. Be sure to remove all the previous JetBrains Mono versions from OS. Installing on top may cause some bugs.

The possible solution for this issue is:
1. Try to delete bundled version of JetBrains Mono. I don't know the exact location this may help to find it https://youtrack.jetbrains.com/issue/IDEA-92825
2. Use non variable version.

**Comment by VincentJoshuaET** [comment]
Will this be fixed? I use variable fonts for Cascadia Code and Fira Code, they work properly. Also JetBrains Mono Italic variable works too.

**Comment by philippnurullin** [comment]
@VincentJoshuaET Did you try to remove the bundled font? 
This issue will not reproduce with Fira or Cascadia because they are not bundled in Android studio.

This problem will be completely eliminated when Android studio will have proper support of font weights.

**Comment by philippnurullin** [comment]
Just saw that i paste the wrong link in my first comment. 
Please go here to have some idea where is bundled fonts are stored https://github.com/JetBrains/JetBrainsMono/issues/142

**Comment by VincentJoshuaET** [comment]
![image](https://user-images.githubusercontent.com/19756326/89625824-0c077f00-d8cb-11ea-849b-635793d2c341.png)

JetBrains Mono is not here. Looks like Fira Code is though. I have never installed the non variable Fira Code fonts, I'm sure this came from the Android Studio installation.

**Comment by philippnurullin** [comment]
Ok, we will try to reproduce it.

**Comment by VincentJoshuaET** [comment]
Thanks, at least I found a workaround to use the non variable fonts only for Android Studio. Just put the non variable ttf files to the IDE fonts folder for now.

**Comment by philippnurullin** [comment]
Just to be clear, you don't need to put files in IDE folder. Install it in OS is ok. It's just some fonts are bundled with IDE & stored in that folder.

We could not reproduce the issue with latest Android studio & JetBrains Mono v2.001.

To make sure there is no font conflict you can delete all JetBrains Mono files from OS manually & reinstall. If this not help i suggest contact the Android Studio support.
