### ISSUE TITLE
Build script returns error

### ISSUE THREAD

**Issue by philippnurullin** [JetBrains/JetBrainsMono#320]
Hi @RosaWagner . Unfortunately i'm having troubles with running `build.sh`.
This is an error im getting
<img width="539" alt="Screenshot 2020-10-02 at 13 13 39" src="https://user-images.githubusercontent.com/48058957/94913076-4b101600-04b1-11eb-92db-bee627fc32ca.png">

**Comment by RosaWagner** [comment]
- Did you installed gftools, fontmake and fontbakery in a virtual environment?
- Did you run the build script from the /sources folder?

I don't know what is UpdateMetaDataKt, it is not in the build script…

**Comment by philippnurullin** [comment]
- `gftools`, `fontmake` and `fontbakery` are installed. Don't know what is virtual enviorenment.
- Yes.

I figured it out why this error is shown. Sorry to bother you. 

But the script still isn't working for me.

**Comment by philippnurullin** [comment]
Looks like there is a problem with python 2.7 on my mac. Installed `gftools`, `fontmake` and `fontbakery` seems to have some problems with it.

**Comment by RosaWagner** [comment]
Virtual environment are made to avoid conflicts in your python packages. If the script is not working it is probably because some stuff are not installed (like homebrew etc) or are in conflicts with your environment (python 2 and 3…). Gftools uses python3, you have to to use "pip3 install" command to install them if your current environment is python 2. 

I am trying to revise the build script and requirements to be able to install everything with pip3 (so no homebrew).

- For now I suggest to create a virtual environment (in your repo of JetBrains Mono)
`python3 -m venv env`
- Activate it:
`source env/bin/activate `
- Install the packages:
```
pip3 install gftools
pip3 install fontmake
pip3 install fontbakery
```

I PR you a patch for the build script to be able to export the variable and the statics with these packages in the virtual env (we will see later a script for the webfonts)

**Comment by RosaWagner** [comment]
We can video call if you need help. These stuff can be sooo overwhelming…

**Comment by philippnurullin** [comment]
Ok. Let's have a video call. I feel it will be faster this way. 
When it will be comfortable for you to do it?

**Comment by RosaWagner** [comment]
I am available in like 5-10min

——

Type design
Font engineering
Typography

+336 76 44 45 83
mail@rosaliewagner.com
www.rosaliewagner.com

**Comment by philippnurullin** [comment]
The script is running, finally.
Don't work with the new sources so this may need your attention. Please look at them when you have time.

**Comment by RosaWagner** [comment]
Ok put them in the repo with another name and I will look at it on Monday

**Comment by philippnurullin** [comment]
Sorry, already pushed them with the old names.

**Comment by RosaWagner** [comment]
I had this response : <https://github.com/googlefonts/fontmake/issues/698>
So it is about something that one master have and not the other two, concerning positioning (anchors, contextual alternate, etc.)

**Comment by philippnurullin** [comment]
Hi @RosaWagner , everything works with variable. 
When the scrip will be ready to export web formats, ttf and ufo packages? It will be nice to make the next release wit it.
