### ISSUE TITLE
Why the head of lowercase l is shorter than its tail? Is it by design?

### ISSUE THREAD

**Issue by CodeCrazy-ywt** [JetBrains/JetBrainsMono#343]
I found that the head of lowercase `l` is shorter than its tail, and I wonder whether it is a new aesthetic design. To me, it's not as beautiful as it was before.
![Screenshot_20201024_180731](https://user-images.githubusercontent.com/62426149/97079120-0ac13500-1624-11eb-86a9-921e8fb6bccd.jpg)

**Comment by philippnurullin** [comment]
Hi @CodeCrazy-ywt . Looks like you switched from very old version. 
Starting from v 1.0.6 the stem of `l` is shifted to the left to render better in low DPI screens. In the size of 13px if its placed in the middle it becomes blurry. 
I'll see what can be improved in the next version, but because this is working like intended i'm closing this issue.
