### ISSUE TITLE
JetBrains Mono User Guide - first draft for review

### ISSUE THREAD

**Issue by kenmcd** [JetBrains/JetBrainsMono#364]
...

**Comment by philippnurullin** [comment]
Well, you deleted it faster that i could looked at it. But thanks for the effort.

**Comment by kenmcd** [comment]
After a couple weeks I figured no one was interested.
If you are interested, and you have the time to review and give feedback, I can post it again.
But I will warn you that there is quite a bit of info required that requires detailed review.
The ligatures listed on the demo page are not complete.
And I can only do so much by trying to reverse-engineer the OpenType code.
Someone who intimately knows what is supposed to happen must take a look.

It is kind of a work-in-progress mess.
It is what I call the _content dump_ first draft - get everything available in there,
and then worry about making it pretty after the content is basically complete. 

So if you are interested and have some time to review it, I can post it again.

**Comment by Omnieboer** [comment]
That's what the space is for I guess, and with comments and further commits, we can workshop your draft together as much as necessary. Maybe it could live in it's own Branch so other people are free to suggest commits? If not, a fork that could be linked here?

**Comment by philippnurullin** [comment]
I'm not 100% sold on idea to have separate .pdf with type specs. The web page is solving this problem. 

But what can be really helpful is a Wiki. On a web page it's difficult to keep it up to date because of the long process of implementation. But Wiki can be edited by community and be easily kept up to date.

So, what if you drop a draft of the Wiki structure. I think it will be nice start. And everybody can contribute.

It's absolutely ok if you don't want to do it. )
