### ISSUE TITLE
Using bold style with JetBrainsMono Medium font breaks the monospacing

### ISSUE THREAD

**Issue by vadersb** [JetBrains/JetBrainsMono#376]
![bold_mono](https://user-images.githubusercontent.com/53225685/99932469-35a8c100-2d69-11eb-983d-b4e0b0d0714b.png)

**Comment by philippnurullin** [comment]
Hi @vadersb Looks like synthetic bold applied by IDE. 
That happens because the Rider (and all IDEs based on IntelliJ core) not supporting font weight changing. So when you selecting the «Medium» weight as the base font it can't find the Bold weight for it. Because it thinks that the _JetBrains Mono Medium_ is a separate font family. But this will be corrected when this issue will be closed https://youtrack.jetbrains.com/issue/IDEA-92825. 

Here is a duplicate issue. https://github.com/JetBrains/JetBrainsMono/issues/267

Closing this issue because it's not a font issue.
