### ISSUE TITLE
Why are some name table FontBakery checks excluded for statics?

### ISSUE THREAD

**Issue by felipesanches** [JetBrains/JetBrainsMono#381]
https://github.com/JetBrains/JetBrainsMono/blob/2c2657fac2db571f0b501e962425276dded2b57e/.github/workflows/fontbakery-ci-statics.yml#L43

It would be good to document the reason why these checks are being skipped. Not running the checks also means some problems may not be automatically detected.

I also noticed that these checks are not excluded when checking variable fonts:
https://github.com/JetBrains/JetBrainsMono/blob/2c2657fac2db571f0b501e962425276dded2b57e/.github/workflows/Fontbakery-ci-variable-fonts.yml#L47

**Comment by philippnurullin** [comment]
Hi @felipesanches . Lets ask @RosaWagner . Maybe she can help with that.

**Comment by RosaWagner** [comment]
Hi, I ignored these checks because the font is named `JetBrains Mono`, and so the `typographic family name` was always failing because of the lack of space in `JetBrains`. What is curious is that it is not a problem in the variable… I think it is and I just forgot to add this ignore flag. I'll have to check it out.

**Comment by philippnurullin** [comment]
I think it's save to close now.
