### ISSUE TITLE
Triple equals rendered poorly

### ISSUE THREAD

**Issue by alexpetrean80** [JetBrains/JetBrainsMono#385]
In PHPStorm triple equals are rendered poorly with Jetbrains Mono, no issue with fallback font(Fira Code)

Jetbrains Mono:
![image](https://user-images.githubusercontent.com/49921909/102046247-99ac2b80-3de3-11eb-8469-d097684491e5.png)

Fira Code:
![image](https://user-images.githubusercontent.com/49921909/102046189-7da88a00-3de3-11eb-8bc2-482d8ea96a54.png)

 
Font size is 14 and line spacing 1.2

**Comment by philippnurullin** [comment]
Hi @alexpetrean80 Closing this issue because it a dublicate of https://github.com/JetBrains/JetBrainsMono/issues/25
You can delete the bundled font and install the latest version. This is improved a lot but not completely vanished starting from v2.200 
This issue will give you an idea how to delete old fonts https://github.com/JetBrains/JetBrainsMono/issues/142
