### ISSUE TITLE
'F' higher than other symbols

### ISSUE THREAD

**Issue by avgoncharov** [JetBrains/JetBrainsMono#40]
In Rider, in C# code, with font size = 15, symbol 'F' higher than other symbols 
![image](https://user-images.githubusercontent.com/2749062/72597167-3fc68b80-391e-11ea-97a5-c72c5116ae50.png)

**Comment by MinusKube** [comment]
And the exact opposite happens in Visual Studio 2019 and JetBrains Mono 1.0.2.
![image](https://user-images.githubusercontent.com/13206601/73787611-f4283480-479b-11ea-9b38-97c669956da2.png)

**Comment by Remi-Tribia** [comment]
![image](https://user-images.githubusercontent.com/40400644/76528460-200c9900-6471-11ea-91e9-d6ae56e8bd12.png)
I got the same result with R and Y too in VS2019, but only at certain zoom values (here 118%)...
At 100% zoom it's correct.

**Comment by philippnurullin** [comment]
@Remi-Tribia Do you experience this kind of problem with other monospaced fonts? What version of JetBrains Mono is installed in your OS?

**Comment by Remi-Tribia** [comment]
I'm not at work atm, I tried at home but couldn't reproduce the issue.

**Comment by philippnurullin** [comment]
@Remi-Tribia What version of the JetBrains Mono you using at home & at work. Are they the same?

**Comment by Remi-Tribia** [comment]
I think it was 1.0.0 on both at the time of my last message.
I made a gif before and after installing 1.0.3 on my work computer, the issue seems to be gone with 1.0.3.

![dif_1 0 0_1 0 3](https://user-images.githubusercontent.com/40400644/76960495-df52cb00-691b-11ea-933a-23bb3fd51856.gif)
I made the capture with Windows magnifier at 400% and VS2019 zoomed at 117%

**Comment by philippnurullin** [comment]
Glad to hear!
