### ISSUE TITLE
'6' character not in line

### ISSUE THREAD

**Issue by sidristij** [JetBrains/JetBrainsMono#42]
![image](https://user-images.githubusercontent.com/1454688/72597658-3c7fcf80-391f-11ea-9111-79774e5078df.png)

**Comment by philippnurullin** [comment]
Hi, it's a bug of the v 0.23 of the JetBrains Mono. Unfortunately, the bundled fonts is always have priority when IDE decided which to use. We are working on correcting this behaviour. This problem will be solved when v 1.0 will be bundled.
To fix it you need to delete the bundled font from it installation folder. That makes the IDEs use the system-wide installed v 1.0

**Comment by philippnurullin** [comment]
@sidristij This problem is cured by removing the bundled fonts, and installing the fresh in the system.

The bundled font files are located:

**Win**

a)`IDEA\jbr\lib\fonts`
b) `If you using Toolbox C:\Users\ username\AppData\Local\JetBrains\Toolbox\apps\CLion\ch-0\193.6015.37\jbr\lib\fonts\`

**Mac**

`IntelliJ\ IDEA.app/Contents/jbr/Contents/Home/lib/fonts/`

And it's important to restart.
