### ISSUE TITLE
Emojii are not monospaced 🥲

### ISSUE THREAD

**Issue by pboling** [JetBrains/JetBrainsMono#422]
Can this be fixed?

Would be nice to be able to use emoji as if they were just another character.

**Comment by trygveaa** [comment]
Emoji are defined in the unicode standard to have a width of two characters in monospaced fonts, so it would be wrong to do anything else.

I didn't know JetBrains Mono had any emoji though, usually emoji come from separate fonts.

**Comment by pboling** [comment]
It would be nice if they followed that guideline and used a monospaced width of two characters!  I looks like the emoji are not in the font, and _I think that may be part of the problem_.  They must be rendered by a mysterious brute force fallback font, even if no fallback is set in the JetBrains IDE.  Is it impossible to resolve this?

<img width="753" alt="Screen Shot 2021-03-25 at 4 47 31 PM" src="https://user-images.githubusercontent.com/19505/112553269-cd570400-8d89-11eb-9b4d-fdabce50be56.png">

**Comment by pboling** [comment]
> Emoji are defined in the unicode standard to have a width of two characters in monospaced fonts, so it would be wrong to do anything else.

It seems that this font is "doing it wrong" then...

**Comment by trygveaa** [comment]
Yeah, that doesn't look right. If you post the file I can check if the characters are a part of this font. If not, you might need to open an issue with the IDE instead of here.

**Comment by pboling** [comment]
Raw: https://gist.githubusercontent.com/pboling/7c63663e10c6f95832bc3dc12ba48c7a/raw/1c8169a9b423f85e99102302db2191c2fbfe4f48/Emoji%2520Monospace%2520Test.md

**Comment by trygveaa** [comment]
Yeah, none of those emoji are in JetBrains Mono. From the looks of it you're getting them from the Apple emoji font (makes sense since you're on mac). It's probably a bug in your IDE that they're not drawn as monospaced.

Here is how it looks for me btw. In kitty:
![image](https://user-images.githubusercontent.com/601966/112558559-58a6b880-8dcf-11eb-8cff-14356593a8ee.png)

And in IntelliJ:
![image](https://user-images.githubusercontent.com/601966/112558695-9d325400-8dcf-11eb-8d74-c7104aebe046.png)

IntelliJ draws the arrows incorrectly, but other than that it's correct. This is with JetBrains Mono for the normal characters and Noto Color Emoji for the emoji.

**Comment by pboling** [comment]
I'll figure out how to file an issue with JetBrains.  Thanks!
