### ISSUE TITLE
Info about variable fonts in Readme

### ISSUE THREAD

**Issue by signalwerk** [JetBrains/JetBrainsMono#43]
It would be cool to have a information about variable font in the readme-file. 

I saw you had it once but it got removed: https://github.com/JetBrains/JetBrainsMono/commit/3e26897adced1371ac942167bf3adb4bb4e62c53

Is this on the roadmap or was it just an experiment.

**Comment by philippnurullin** [comment]
At early stages we had variable function with  x-height, weight and width (Yes we had the Expanded version of JetBrains Mono too). But we decided to stop the development in this way, mainly because of small team vs complexity of this task. We will return to variable function after thinner weights are released.

**Comment by signalwerk** [comment]
@philippnurullin this is super awesome! looking forward for a VF with a weight-axis 🤓
