### ISSUE TITLE
Ligature => not rendered correctly

### ISSUE THREAD

**Issue by jonathanwiesel** [JetBrains/JetBrainsMono#437]
I switched to a new Macbook Air M1, macOS 11.3 and the `=>` ligature fails to render correctly

![Screenshot 2021-05-13 at 16 04 09](https://user-images.githubusercontent.com/1326781/118145381-d66d6480-b40d-11eb-9290-d3ca0a1a1b6f.png)

**Comment by philippnurullin** [comment]
Hi @jonathanwiesel .
This issue is dublicating → https://github.com/JetBrains/JetBrainsMono/issues/431

To fix this:
1. Remove all JB Mono Fonts from OS
2. Download latest fonts from Master https://github.com/JetBrains/JetBrainsMono/tree/master/fonts
3. Install it in the OS

Please reach to me if this will not help.

**Comment by jonathanwiesel** [comment]
Works correctly now, thank you @philippnurullin
