### ISSUE TITLE
box not enough square

### ISSUE THREAD

**Issue by bluelovers** [JetBrains/JetBrainsMono#469]
![image](https://user-images.githubusercontent.com/167966/124875135-20805a00-dffb-11eb-827d-9b632af88aa2.png)

```js
console.log(`
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█ ▄▄▄▄▄ ██ ▄ ▄█ ▄▄▄▄▄ █
█ █   █ █▀ ▀▀██ █   █ █
█ █▄▄▄█ █▄█ ▄ █ █▄▄▄█ █
█▄▄▄▄▄▄▄█▄▀ ▀ █▄▄▄▄▄▄▄█
█▄▄▀▀▀ ▄ ▀ ▀█ █▀█ ▄▀▀██
█ ██ ██▄█▄▄▀▄█▄██ ▀▀▄██
██▄▄██▄▄█▀▄▄▀▀▀ ▀█ ▀▄▀█
█ ▄▄▄▄▄ █ ▄▀▀ ▀▄ ▀  ▄▀█
█ █   █ ███ █ ██▄█▀▀▄██
█ █▄▄▄█ █▀▀ ███▄█▀▄▀▄▄█
█▄▄▄▄▄▄▄█▄██▄█▄██▄█▄▄██
`)
```

expected result

![image](https://user-images.githubusercontent.com/167966/124875702-c8962300-dffb-11eb-8b75-d5329fb3f915.png)

What happens instead

![image](https://user-images.githubusercontent.com/167966/124875167-2a09c200-dffb-11eb-8ea2-1a1097528316.png)

https://github.com/JetBrains/JetBrainsMono/issues/113
https://github.com/JetBrains/JetBrainsMono/issues/84
https://github.com/JetBrains/JetBrainsMono/issues/165

**Comment by CodeCrazy-ywt** [comment]
Since Jetbrains Mono is a **monospaced** font, every character should be equally wide. So it's not that possible for boxdrawings to fit in squares.

**Comment by philippnurullin** [comment]
Hi @bluelovers 
Unfortunately the FullBlock (u+2588) can't be square. 

- It width is equal to the width of all letters. If we modify it the font won't be monospaced.
- It height is equal to the font vertical metrics. It can't be changed too because making it less tall (more square), will lead to very small line height. And will lead to all font collapsing.

Closing this issue because it is a conflicting with the font.
