### ISSUE TITLE
error when upgrading to latest version via homebrew

### ISSUE THREAD

**Issue by rinkjames** [JetBrains/JetBrainsMono#477]
Is this a homebrew/cask issue or a JetbrainMono issue?
<img width="1060" alt="Screenshot 2021-07-30 at 09 41 04" src="https://user-images.githubusercontent.com/13288151/127618991-fb368a64-b180-49db-8cfb-066bf676c0b5.png">
<img width="1392" alt="Screenshot 2021-07-30 at 09 43 27" src="https://user-images.githubusercontent.com/13288151/127619101-d35ef482-e6d4-44d7-a847-e21a8346622f.png">

**Comment by philippnurullin** [comment]
As I understand it the problem is that you don't have the file so homebrew can't update it.
Homebrew takes files from official release zip. Just checked, everything is ok with it, all the font files are there.

As a solution you can manually copy missing file from here https://github.com/JetBrains/JetBrainsMono/tree/master/fonts/variable
This will potentially solve similar problem in the future.

Or you can do nothing. Because variable files duplicating all the font you already have. It is the same font but in different format.

**Comment by rinkjames** [comment]
> As I understand it the problem is that you don't have the file so homebrew can't update it.
> Homebrew takes files from official release zip. Just checked, everything is ok with it, all the font files are there.
> 
> As a solution you can manually copy missing file from here https://github.com/JetBrains/JetBrainsMono/tree/master/fonts/variable
> This will potentially solve similar problem in the future.
> 
> Or you can do nothing. Because variable files duplicating all the fonts you already have. It is the same font but in different format.

Ok thanks. It's a weird, as I installed using Hoembrew and didn't touch the font files, so I'm not sure how I lost any relevant files... Manually placing the variable files there worked though.

**Comment by philippnurullin** [comment]
Looks like the fonts was removed manually. → https://github.com/Homebrew/homebrew-cask-fonts/pull/3916
