### ISSUE TITLE
enabling stylistic sets and contextual variants in NL

### ISSUE THREAD

**Issue by nashpatty** [JetBrains/JetBrainsMono#562]
Hey, I'm unable to switch to stylistic sets and contextual variants in Jetbrains Mono NL, from the latest [2.300 downloads](https://github.com/JetBrains/JetBrainsMono/tree/master/fonts/ttf). 
I wanted to see how they looked in an actual coding environment. They look beautiful, but it would be nice to enable them in NL version of the font.
Jetbrains Mono:
<img width="910" alt="image" src="https://user-images.githubusercontent.com/28615881/193625686-d98ad2d6-1deb-4de6-bd83-d1eedeabc9fb.png">

Jetbrains Mono NL:
<img width="918" alt="image" src="https://user-images.githubusercontent.com/28615881/193625818-9feb2a11-0e98-4500-913e-4f5b76f02c6d.png">

**Comment by philippnurullin** [comment]
Hi, @nashpatty Thanks for liking the new alternates.
Yes, currently the NL version is stripped of all OpenType features. 
NL version is made for IDE & editors that don't support OpenType features and don't have the ability to switch off ligatures.

If your IDE or editor supports OT features, you can tune the font with alternates and turn off the ligatures. 

Closing because all works like intended.
