### ISSUE TITLE
Add Udmurt language

### ISSUE THREAD

**Issue by codemurt** [JetBrains/JetBrainsMono#569]
Thank you for such a cool font. The list of supported languages has Erzya, Karelian and other languages, but Udmurt language isn't there. If it's possible, please add support for Udmurt language. Udmurt alphabet has five additional letters (Ӝӝ, Ӟӟ, Ӥӥ, Ӧӧ, Ӵӵ) to the Russian alphabet.

**Comment by philippnurullin** [comment]
Hi @codemurt 
Please try to type thees letter in JetBrains Mono. I believe the Udmurt is supported.
If you have any trouble or it's not in your case, please let me know.

**Comment by YtotheWT** [comment]
In v2.301, these letters are *not* supported.
![image](https://user-images.githubusercontent.com/62426149/197747807-403b26c1-346e-4f84-b869-42234ecc5928.png)

**Comment by philippnurullin** [comment]
@YtotheWT 
There are no actual letters in the Font. But a text editor can combine a base letter, for example Ж, with a _mark_ `diresis` to produce the final letter. 

In your example, there is something wrong with the font or editor. As I can see the editor can not find the base letter and the _mark_. Which is very strange because JetBrains Mono have these two symbols from a first release 2 years ago. 
It looks like you using _font preview_ for testing. Correct me if I'm wrong. Please test it in a couple more text editors, because font preview might be not the best way to do it.

**Comment by codemurt** [comment]
JetBrains Mono and JetBrains Mono ExtraBold
![image](https://user-images.githubusercontent.com/19909792/197755865-3eac5cd8-a47c-4715-85eb-4660fd14d23e.png)

**Comment by philippnurullin** [comment]
@codemurt Thnaks.

What text editor did you use?

To exclude any problems or errors, I will add the symbols in the next update.
