### ISSUE TITLE
Needs thinner font weight

### ISSUE THREAD

**Issue by Jeff11** [JetBrains/JetBrainsMono#66]
For me the font is too bold. I would welcome a thinner version.

Setup:
Android Studio 4.0 Canary 8
Build #AI-193.5233.102.40.6107147, built on January 2, 2020
Runtime version: 1.8.0_212-release-1586-b4-5784211 x86_64
macOS 10.15.2
non retina monitor
font size 13

It gets better with Subpixel Antialiasing turned off, but that's not very eye pleasing.

Screenshots and comparison with Fira Code here:
https://intellij-support.jetbrains.com/hc/en-us/requests/2453835

**Comment by philippnurullin** [comment]
@Jeff11 Looks like it's a bug. The image with JetBrains Mono is set in Bold weight. We had a few of such reports & continue to research the problem.
Thank you for feedback!

**Comment by ddotlic** [comment]
@philippnurullin If this helps... I have noticed something similar. Am using macOS 10.15.2 and v1.0.1 of the font and VS Code as the editor (a fairly popular choice) on a LG 5K screen (logical resolution 2560x1440, so-called "retina" mode).

1. If I just set "JetBrains Mono" as a font in VS Code, it works but the font is a bit too heavy for my taste. Adjusting font weights does nothing; IMHO, adjusting font weight should result in variations like "Regular", "Medium", "Bold" etc. be used
2. If I set "JetBrains Mono Regular" or "JetBrains Mono Medium" (or I guess any other 'concrete' variation) as a font and _then_ change the font weight, things work as expected.
3. Interestingly, using the same "JetBrains Mono" in GitKraken (a GUI git client) which internally uses VS Code for source code display, I _am_ getting a thinner font rendering. Who's (if anyone) at fault is beyond me, am just a font user.

OTOH, this might be normal, if so, just ignore my comments 😉 since I have a workaround.

**Comment by snaggen** [comment]
I prefer light fonts. Currently using Source Code Pro Light, but thinks JetBrains Mono looks very interesting but would prefer to have a Light version.

**Comment by Jeff11** [comment]
Version 1.0.2 is a tiny bit thinner. Added screenshots to the link in OP.

**Comment by ddotlic** [comment]
@Jeff11 Nice to hear you're actually doing something based on your user's comments, kudos!

To maybe clarify my point: the font is IMHO thin enough but something is "broken" in its configuration such that some tools - like VS Code - do not end up using the correct weight simply by using the "JetBrains Mono" and the font weight setting. While a workaround exists (specify 'full' name like "JetBrains Mono Regular") it might not be obvious. This particular thing is hopefully easier to fix than modifying the weight of the whole font... Cheers!

**Comment by Jeff11** [comment]
@ddotlic have you tried the font version 1.0.2 yet? I guess the rendering is now correct and that I just prefer a thinner font.

**Comment by ddotlic** [comment]
@Jeff11 I have, the issue is still there - unless I explicitly say "... Regular" the font weight won't be respected (at least not in the way I'd expect it to be, which isn't necessarily correct).

**Comment by qgates** [comment]
I would also love to see a light/sharp version of JBM. On certain screen / OS combos, even Regular looks a tad heavy compared with Fira Code or Consolas, at least to me, and especially when using it as a terminal font.

**Comment by richardbushell** [comment]
+1 for a LIGHT(ER) weight in the family too!

**Comment by philippnurullin** [comment]
@ddotlic Reorganised the Font family structure in v1.0.3. This should fix this problem. Do you still have the issues with weight choosing?

**Comment by ddotlic** [comment]
@philippnurullin Yes, I still see the issue. It turned out I previously did not "correctly" (macOS seems to require I remove the font before installing the one with the same name, it ignores the version) install 1.0.2 but have made sure now that I'm running 1.0.3.

Choosing just "JetBrains Mono" results in (for my taste) fairly weighty font. Setting weight to the lowest possible value (100) does nothing visible. Setting it to the highest value (or anything above 500) does make it heavier, though 😄 

Switching to "JetBrains Mono Regular" makes the font slightly wider (?!) and _then_ reducing the weight to 100-200 does finally result in a font thin enough for myself 😉

**Comment by philippnurullin** [comment]
@ddotlic The current numbers of weights in the font family is 4. The thinest, at the moment is Regular, which is classified as 400, following by the Medium as 500, Bold as 700, ExtraBold as 800. So, if the problem is that you want to use something more lighter that 400, there is no such weight in JetBrains Mono now. 

I suppose that the other weights you getting are from your fallback font. Can you provide the screenshots, that i can understand you better.

**Comment by ddotlic** [comment]
@philippnurullin Aha, you just nailed it! What I was getting was my fallback `Fira Code` which is very similar, so I did not notice 🤣 OK, let me join the others in asking you for a thinner version - say, "Light" - of this font, pretty please? With sugar on top?

**Comment by ddotlic** [comment]
@philippnurullin In fact, based on the differences between other weights, "Extra Light" might work too 😉 On high resolution "retina" screens these lighter weight fonts look _much_ better (yes, personal opinion, not claiming anything, but a few users do seem to agree with me). Since one of the main "competitors" of this font is "Fira Code" please check their own light version and their weights and you'll see what I mean.

**Comment by ddotlic** [comment]
@philippnurullin And yes, I have no idea how much work this is, doesn't stop me from dreaming. Thanks for the effort so far!

**Comment by philippnurullin** [comment]
@ddotlic Then this issue is duplicated here https://github.com/JetBrains/JetBrainsMono/issues/1 
The short answer is that the lighter version are in progress, but cant say the exact date now.

I don't see Fira Code as competitor, but more as an ally in brining the good experience to developers, as Cascadia, or many good fonts out there. In matter of features, all will be equal in time. But each of them have it's uniq feeling, which is matter of personal taste. So we just giving the more broad choice.

**Comment by ddotlic** [comment]
> The short answer is that the lighter version are in progress

That's awesome! Subscribed to updates to #1 to make sure I am notified when it is done. Thanks!

> I don't see Fira Code as competitor, 

Of course not, that's why I put quotes around it 😉 same goes for Cascadia - which incidentally _also_ is fairly "fat" for my taste, to the point where I couldn't overlook it. Thanks again for listening!

**Comment by qgates** [comment]
> I don't see Fira Code as competitor, but more as an ally in brining the good experience to developers, as Cascadia, or many good fonts out there. In matter of features, all will be equal in time. But each of them have it's uniq feeling, which is matter of personal taste. So we just giving the more broad choice.

I couldn't agree more. I also like Fira Code though it's never been my go to because ligatures matter less to me than readability. For me Fira's `r` and `f` always grated, even though there is a stylistic set to fix `r` in newer versions. And Fira lacks an italic variant, so italics are just slanted versions of normal type. That doesn't look nice and collapses whitespace to the right where italic words meet normal type.

**Comment by ozmium** [comment]
I have the same problem, even when using JetBrains Mono version 1.0.3. Some apps recognize the thin "Regular" font, whereas other apps do not.

- IntelliJ IDEA 2019.3.3, Google Chrome and Firefox all use the thinner Regular font by default.

- But Android Studio 3.6 / 3.5 and BBEdit 13 use the bold font by default. There is no way to specify using "JetBrains Mono Regular" in these apps.

Screenshot attached for comparison.

![JetBrains Mono - IntelliJ IDEA vs Android Studio, Mac](https://user-images.githubusercontent.com/6191136/75971823-3abb9c80-5eca-11ea-876f-a273e650e759.png)

**Comment by ddotlic** [comment]
@ozmium The argument in this item is that `Regular` isn't thin enough.

Funny though, when using JetBrans products on a "retina" screen in macOS, one _can_ make things quite a bit easier on the eyes (from the perspective of someone wishing for thinner fonts): go to `Preferences`, then `Appearance & Behavior` and finally `Appearance`; on the right, scroll down to the `Antialiasing` section and for the `Editor` choose `No antialiasing`. 

The rendering of this font is visibly thinner than in, say, VS Code (which _is_ aware of the weight and does use the `Regular` font when told to).

Hope this helps someone 😉

**Comment by philippnurullin** [comment]
@ozmium Hi. Android studio is based on the IntelliJ IDEA core, so i believe this ticket is about this problem https://youtrack.jetbrains.com/issue/IDEA-224652. Sadly, still not fixed. 

Regarding the BBedit 13 i recommend contacting their support. I'm pretty sure that this is a software problem. But please contact me if it's not.

**Comment by ddotlic** [comment]
One more thing, I feel so stupid... if you are on a macOS and using a "retina" screen, even in VSCode you can get "better" (read: thinner) rendering of this font by changing the (duh!) `  workbench.fontAliasing`.

You can set it to either `none` (thinner, but doesn't look great) or `antialiased` (thinner, but forces antialiasing) or my personal preference `auto` which picks for you based on the screen DPI. The default value named `default` will do sub-pixel font smoothing which looks visibly thicker on "retina" (high DPI screens).

IMHO, `auto` should be the default value but whatever... this makes it much easier waiting for the #1 to land.
